### ISSUE TITLE
udp send-receive 

### ISSUE THREAD

**Issue by apressas** [jandejongh/udp2eth#1]
Hello,

I am generating udp packets to Server Address:0.0.0.0:1235 from one DSRC box and expecting to receive them at Client address: 127.0.0.1:1236 on another, as shown by udp2eth terminal output, but it just does not seem to happen. Packets are generated alright since **ifconfig** gives me the number of TX packets, but I am not receiving them on the other end. I know that the two stations are configured properly because my receiving side does read the 8 packets sent when doing **iw dev wlan0 ocb join 5900 10MHZ** from the other one. 

Am I missing something regarding how the packets should be sent to udp2eth, or how should the program be used in general? Btw should I generate broadcast packets and send to udp2eth or is that not important? 

Best,
Andreas

**Comment by jandejongh** [comment]
Hi Andreas,

First, thanks for the feedback and apologies for the lack of a user manual :-). Never found the time to finish that.

I'm not sure I can help since I do not understand your setup from the description. The typical use of udp2eth is to select an (Ethernet) interface, server port (address) and client address through the command-line interface. Anything you send to the server port over UDP is then 'bridged' to the Ethernet device, and you'll need to construct the Ethernet frame yourself. Anything received on the device is embedded into a UDP datagram and sent to the client address you provide.
Are you sure you are generating proper Ethernet frames (including header?).
By the way, you can use 0.0.0.0 for binding 'to any interface', but you cannot use it as a destination IP address.

Are you sure you're not running Windows and bump into a firewall/permission problem? If you run udp2eth in 'verbose' mode, it should output every frame received from the Ethernet device.
